import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/MainNav/MainNav";
import { Box, Toolbar } from "@mui/material";
import Providers from "./providers/Providers";

const roboto = Roboto({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <Providers>
          <Box sx={{ display: "flex" }}>
            <MainNav />
            <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
              <Toolbar />
              {children}
            </Box>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
